version: "3.8"
services:
  magazine:
    container_name: sarenzamag
    image: srzlab.azurecr.io/magazine:1.0.0
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - STRAPI_SERVICE_HOST=strapi.dev.sarenza.corp
      - STRAPI_SERVICE_PORT=80
      - STRAPI_SERVICE_SCHEME=http
      - STRAPI_CDN_PREFIX=/magazine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 443:5000