version: "3.8"
services:
  magazine:
    container_name: sarenzamag
    image: srzlab.azurecr.io/magazine:1.0.0
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - STRAPI_SERVICE_HOST=yolo01.sarenza.archi
      - STRAPI_SERVICE_PORT=1337
      - STRAPI_SERVICE_SCHEME=http
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 443:5000