apiVersion: v1
kind: Service
metadata:
  name: {{ include "sarenza-digitalexperience-magazine.fullname" . }}
  labels:
{{ include "sarenza-digitalexperience-magazine.labels" . | indent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sarenza-digitalexperience-magazine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
