import React, { useState, useEffect } from "react";
import { getMenu } from "../../strapi/strapi.service";
import cn from "classnames";
import SubMenu from "./subMenu";

const Menu = () => {
  const [menus, setMenus] = useState([]);
  useEffect(async () => {
    const menus = await getMenu();
    setMenus(menus);
  }, []);
  const [openMenu, setOpenMenu] = useState(false);
  return (
    <div className="no-touch">
      <header id="MainHeader-RD">
        <div id="InnerMainHeader">
          {/* Touch optimisation */}
          <div
            id="MainNavOpener"
            onClick={() => {
              setOpenMenu(show => !show);
            }}
          >
            Menu
          </div>
          <div id="MainNavOverlay" style={{ display: "none", opacity: 1 }} />
          {/* Logo */}
          <a href="/" className="sprited logo" data-track-label="Logo">
            Chaussures et sacs sarenza.com
          </a>
          {/* Site navigation - Start */}
          {/* WILL BE GENERATED BY CMS Tool */}
          <nav
            id="MainNav-RD"
            className={cn({
              ["open"]: openMenu
            })}
          >
            <a className="back" href="#0">
              Menu
            </a>
            <span
              className="closer"
              onClick={() => {
                setOpenMenu(show => !show);
              }}
            >
              Fermer
            </span>
            <div className="inner-scroll">
              <ul className="menu-group-list  active">
                <li data-menu-group={1} className="group-tab ">
                  <a href="/chaussure-femme">Femme</a>
                </li>
                <li data-menu-group={2} className="group-tab active">
                  <a href="/chaussure-homme">Homme</a>
                </li>
                <li data-menu-group={3} className="group-tab ">
                  <a href="/chaussure-enfant">Enfant</a>
                </li>
                <li data-menu-group={1} className="group-root ">
                  <a href="/chaussure-femme">Inspiration</a>
                </li>
                <li data-menu-group={2} className="group-root active">
                  <a href="/chaussure-homme">Inspiration</a>
                </li>
                <li data-menu-group={3} className="group-root ">
                  <a href="/chaussure-enfant">Inspiration</a>
                </li>
              </ul>
              <ul className="main-list">
                {/* [RD] - MegaMenu Item men: début */}
                <style
                  dangerouslySetInnerHTML={{
                    __html:
                      "\n      .Picto1:after{ content:' New'; color:#ff2157; font-size:10px;margin:2px 0 0 6px;position:absolute;text-transform:uppercase;}\n\n"
                  }}
                />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  "
                    data-promo
                    data-ea
                    href="/chaussure-nouvelle-collection-homme"
                  >
                    Nouveautés
                  </a>
                  <div className="sub">
                    <div className="sub-inner">
                      <a className="back" href="#0">
                        Retour
                      </a>
                      <a
                        className="root  "
                        data-promo
                        data-ea
                        href="/chaussure-nouvelle-collection-homme"
                      >
                        Afficher tout
                      </a>
                      <div className="col">
                        <span className="title">
                          <span>Nouveautés</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-homme"
                              data-ea
                              className
                            >
                              Chaussures
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&type=122&sort=newest"
                              data-ea
                              className
                            >
                              Vêtements
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/gender/list/view?gender=4&sub_gender=10&sort=newest"
                              data-ea
                              className
                            >
                              Sacs
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/gender/list/view?gender=8&att_gender=625"
                              data-ea
                              className
                            >
                              Accessoires
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/selection-accessoires"
                              data-ea
                              className="Picto1"
                            >
                              Masques "grand public"
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/offre-hygiene-et-beaute"
                              data-ea
                              className="Picto1"
                            >
                              Hygiène &amp; Beauté
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/selection-mode-homme-6"
                              data-ea
                              className="Picto1"
                            >
                              Equipements de sport
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/offre-jouets-general"
                              data-ea
                              className="Picto1"
                            >
                              Jouets
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/marques-ecoresponsables-homme"
                              data-ea
                              className="Picto1"
                            >
                              Mode responsable
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-homme" data-ea className>
                              Tendances &amp; marques du moment
                            </a>
                          </li>
                          <li className="all">
                            <a
                              href="/chaussure-nouvelle-collection-homme"
                              data-ea
                            >
                              Encore plus de nouveautés
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Marques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-adidas-originals"
                              data-ea
                              className
                            >
                              adidas Originals
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-clarks"
                              data-ea
                              className
                            >
                              Clarks
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-converse"
                              data-ea
                              className
                            >
                              Converse
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-geox"
                              data-ea
                              className
                            >
                              Geox
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-nouvelle-collection-nike"
                              data-ea
                              className
                            >
                              Nike
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1663&type=122"
                              data-ea
                              className
                            >
                              Farah
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=823&type=122"
                              data-ea
                              className
                            >
                              Faguo
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1690&type=122"
                              data-ea
                              className
                            >
                              Harris Wilson
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=918&type=122"
                              data-ea
                              className
                            >
                              Lacoste
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=167&type=122"
                              data-ea
                              className
                            >
                              Levi’s
                            </a>
                          </li>
                          <li className="all">
                            <a href="/chaussure-marque-homme" data-ea>
                              Encore plus de marques{" "}
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="mea">
                        <a
                          className="tg ea-tracker ea-print"
                          data-ea="200520_COM_MM_H_ME_DIFF_ECORESPONSABLE_MMN_CHAUSSURES-TEXTILE-SACS"
                          href="/marques-ecoresponsables-homme"
                          style={{ background: "White" }}
                        >
                          <div className="media">
                            <img
                              className="lazy lazy-set"
                              src="https://cdn.sarenza.net/v3/Prod/visuels-site/PE20/200423_Ecoresponsable_shoes_H_mm.jpg?v=20200701104041"
                              data-original="https://cdn.sarenza.net/v3/Prod/visuels-site/PE20/200423_Ecoresponsable_shoes_H_mm.jpg?v=20200701104041"
                              style={{}}
                            />
                          </div>
                          <div className="headline">Penser à demain ❤</div>
                          <div className="title-level3">
                            Nos marques éco-responsables
                          </div>
                          <div className="button">Je découvre</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style
                  dangerouslySetInnerHTML={{
                    __html:
                      "\n      .Picto2:after{ content:' Promo'; color:#ff2157; font-size:10px;margin:2px 0 0 6px;position:absolute;text-transform:uppercase;}\n\n"
                  }}
                />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  "
                    data-promo
                    data-ea
                    href="/tout-chaussure-homme"
                  >
                    Chaussures
                  </a>
                  <div className="sub">
                    <div className="sub-inner">
                      <a className="back" href="#0">
                        Retour
                      </a>
                      <a
                        className="root  "
                        data-promo
                        data-ea
                        href="/tout-chaussure-homme"
                      >
                        Afficher tout
                      </a>
                      <div className="col">
                        <span className="title">
                          <span>Chaussures</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a href="/baskets-homme" data-ea className>
                              Baskets
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/bottes-homme" data-ea className>
                              Bottes
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/bottines-et-boots-homme"
                              data-ea
                              className
                            >
                              Bottines et boots
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussons-homme" data-ea className>
                              Chaussons
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussures-a-lacets-homme"
                              data-ea
                              className
                            >
                              Chaussures à lacets
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-bateau-homme" data-ea className>
                              Chaussures bateau
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussures-a-scratch-homme"
                              data-ea
                              className
                            >
                              Chaussures à scratch
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussures-de-sport-homme"
                              data-ea
                              className
                            >
                              Chaussures de sport
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/mocassins-homme" data-ea className>
                              Mocassins
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-pas-cher-homme"
                              data-ea
                              className="Picto2"
                            >
                              Toutes nos chaussures en
                            </a>
                          </li>
                          <li className="all">
                            <a href="/tout-chaussure-homme" data-ea>
                              Encore plus de chaussures
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Marques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/chaussure-adidas-originals-homme"
                              data-ea
                              className
                            >
                              adidas Originals
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-clarks-homme" data-ea className>
                              Clarks
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-converse-homme"
                              data-ea
                              className
                            >
                              Converse
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-geox-homme" data-ea className>
                              Geox
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-lacoste-homme"
                              data-ea
                              className
                            >
                              Lacoste
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-marvin-co-homme"
                              data-ea
                              className
                            >
                              Marvin &amp; Co
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-new-balance-homme"
                              data-ea
                              className
                            >
                              New Balance
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-nike-homme" data-ea className>
                              Nike
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-timberland-homme"
                              data-ea
                              className
                            >
                              Timberland
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-vans-homme" data-ea className>
                              Vans
                            </a>
                          </li>
                          <li className="all">
                            <a href="/chaussure-marque-homme" data-ea>
                              Encore plus de marques
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="mea">
                        <a
                          className="tg ea-tracker ea-print"
                          data-ea="200904_COM_MM_H_MAJPR_OPPB_OP-METEO_MMC_CHAUSSURES"
                          href="/operation-promo-homme"
                          style={{ background: "#ffffff" }}
                        >
                          <div className="media">
                            <img
                              className="lazy lazy-set"
                              src="https://cdn.sarenza.net//v3/Prod/visuels-site/AH20-21/op_meteo_MM_COM_BEFR_CHFR.JPG?v=20200701104041"
                              data-original="https://cdn.sarenza.net//v3/Prod/visuels-site/AH20-21/op_meteo_MM_COM_BEFR_CHFR.JPG?v=20200701104041"
                              style={{}}
                            />
                          </div>
                          <div className="headline" />
                          <div className="title-level3">Jusqu'à -50%</div>
                          <div className="button">Je fonce !</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style dangerouslySetInnerHTML={{ __html: "\n\n" }} />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  "
                    data-promo
                    data-ea
                    href="/vetements-homme"
                  >
                    Vêtements
                  </a>
                  <div className="sub">
                    <div
                      className="sub-inner"
                      style={{
                        opacity: "0.0257828",
                        height: 0,
                        display: "none"
                      }}
                    >
                      <a className="back" href="#0">
                        Retour
                      </a>
                      <a
                        className="root  "
                        data-promo
                        data-ea
                        href="/vetements-homme"
                      >
                        Afficher tout
                      </a>
                      <div className="col">
                        <span className="title">
                          <span>Vêtements</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/vestes-et-manteaux-homme"
                              data-ea
                              className
                            >
                              Vestes et manteaux
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/pulls-et-gilets-homme" data-ea className>
                              Pulls et gilets
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sweats-homme" data-ea className>
                              Sweats
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/t-shirts-et-polos-homme"
                              data-ea
                              className
                            >
                              T-shirts et polos
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chemises-homme" data-ea className>
                              Chemises
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/pantalons-homme" data-ea className>
                              Pantalons
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/jeans-homme" data-ea className>
                              Jeans
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/tenues-de-sport-homme" data-ea className>
                              Tenues de sport
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/shorts-et-bermudas-homme"
                              data-ea
                              className
                            >
                              Shorts et bermudas
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/shorts-et-slips-de-bain-homme"
                              data-ea
                              className
                            >
                              Shorts et slips de bains
                            </a>
                          </li>
                          <li className="all">
                            <a href="/vetements-homme" data-ea>
                              Encore plus de vêtements
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span> Marques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1626&type=122"
                              data-ea
                              className
                            >
                              Armor Lux
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1663&type=122"
                              data-ea
                              className
                            >
                              Farah
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=823&type=122"
                              data-ea
                              className
                            >
                              Faguo
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1623&type=122"
                              data-ea
                              className
                            >
                              K-Way
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=918&type=122"
                              data-ea
                              className
                            >
                              Lacoste
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=167&type=122"
                              data-ea
                              className
                            >
                              Levi’s
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=969&type=122"
                              data-ea
                              className
                            >
                              Polo Ralph Lauren
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/att_gender-type/list/view?att_gender=625&brand=1631&type=122"
                              data-ea
                              className
                            >
                              Tommy Jeans
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="mea">
                        <a
                          className="tg ea-tracker ea-print"
                          data-ea="200904_COM_MM_H_MAJPR_OPPB_OP-METEO_MMT_TEXTILE"
                          href="/operation-promo-vetement-homme"
                          style={{ background: "#ffffff" }}
                        >
                          <div className="media">
                            <img
                              className="lazy lazy-set"
                              src="https://cdn.sarenza.net//v3/Prod/visuels-site/AH20-21/op_meteo_MM_COM_BEFR_CHFR.JPG?v=20200701104041"
                              data-original="https://cdn.sarenza.net//v3/Prod/visuels-site/AH20-21/op_meteo_MM_COM_BEFR_CHFR.JPG?v=20200701104041"
                              style={{}}
                            />
                          </div>
                          <div className="headline" />
                          <div className="title-level3">Jusqu'à -50%</div>
                          <div className="button">Je fonce !</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style
                  dangerouslySetInnerHTML={{
                    __html:
                      "\n      .Picto2:after{ content:' Promo'; color:#ff2157; font-size:10px;margin:2px 0 0 6px;position:absolute;text-transform:uppercase;}\n\n"
                  }}
                />
                <li className="menu-group" data-menu-group={2}>
                  <a className="tab  " data-promo data-ea href="/sac-homme">
                    Sacs et accessoires
                  </a>
                  <div className="sub">
                    <div
                      className="sub-inner"
                      style={{
                        opacity: "0.199371",
                        height: 0,
                        display: "none"
                      }}
                    >
                      <a className="back" href="#0">
                        Retour
                      </a>
                      <a
                        className="root  "
                        data-promo
                        data-ea
                        href="/sac-homme"
                      >
                        Sacs et accessoires
                      </a>
                      <div className="col">
                        <span className="title">
                          <span>Sacs</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a href="/bagages" data-ea className>
                              Bagages
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/business" data-ea className>
                              Business
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/store/product/gender-type/list/view?gender=4&sub_gender=10&type=56"
                              data-ea
                              className
                            >
                              Petite maroquinerie
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sacs-a-dos" data-ea className>
                              Sacs à dos
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sacs-bandoulieres" data-ea className>
                              Sacs bandoulières
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sacs-sport" data-ea className>
                              Sacs de sport
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sacs-homme" data-ea className>
                              Sacs bandoulières homme
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/sacs-ordinateur" data-ea className>
                              Sacs ordinateur
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/sacs-pas-cher-homme"
                              data-ea
                              className="Picto2"
                            >
                              Tous nos sacs en
                            </a>
                          </li>
                          <li className="all">
                            <a href="/sac-homme" data-ea>
                              Encore plus de sacs
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Accessoires</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a href="/bonnets" data-ea className>
                              Bonnets
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/casquettes" data-ea className>
                              Casquettes
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/ceintures" data-ea className>
                              Ceintures
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chausse-pieds-et-tire-bottes"
                              data-ea
                              className
                            >
                              Chausse-pieds et tire-bottes
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussettes-et-collants"
                              data-ea
                              className
                            >
                              Chaussettes et collants
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/echarpes-et-foulards" data-ea className>
                              Echarpes et foulards
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/gants" data-ea className>
                              Gants
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/lacets" data-ea className>
                              Lacets
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/selection-accessoires"
                              data-ea
                              className="Picto1"
                            >
                              Masques "grand public"
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/selection-mode-homme-6"
                              data-ea
                              className="Picto1"
                            >
                              Equipements de sport
                            </a>
                          </li>
                          <li className="all">
                            <a href="/tout-accessoires" data-ea>
                              Encore plus d'accessoires
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Marques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/accessoires-adidas-performance"
                              data-ea
                              className
                            >
                              adidas Performance
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/accessoires-asics" data-ea className>
                              Asics
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/accessoires-dim" data-ea className>
                              Dim
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/accessoires-falke" data-ea className>
                              Falke
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/accessoires-happy-socks"
                              data-ea
                              className
                            >
                              Happy Socks
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/accessoires-nike" data-ea className>
                              Nike
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/accessoires-puma-socks" data-ea className>
                              Puma Socks
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/accessoires-sarenza-wear"
                              data-ea
                              className
                            >
                              Sarenza Wear
                            </a>
                          </li>
                          <li className="all">
                            <a href="/tout-accessoires" data-ea>
                              Encore plus de marques
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style dangerouslySetInnerHTML={{ __html: "\n\n" }} />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  "
                    data-promo
                    data-ea
                    href="/chaussure-marque-homme"
                  >
                    Marques
                  </a>
                  <div className="sub">
                    <div className="sub-inner">
                      <a className="back" href="#0">
                        Retour
                      </a>
                      <a
                        className="root  "
                        data-promo
                        data-ea
                        href="/chaussure-marque-homme"
                      >
                        Marques
                      </a>
                      <div className="col">
                        <span className="title">
                          <span>Top Marques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a href="/chaussure-nike-homme" data-ea className>
                              Nike
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-adidas-originals-homme"
                              data-ea
                              className
                            >
                              adidas Originals
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-geox-homme" data-ea className>
                              Geox
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-new-balance-homme"
                              data-ea
                              className
                            >
                              New Balance
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-converse-homme"
                              data-ea
                              className
                            >
                              Converse
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-timberland-homme"
                              data-ea
                              className
                            >
                              Timberland
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-birkenstock-homme"
                              data-ea
                              className
                            >
                              Birkenstock
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-clarks-homme" data-ea className>
                              Clarks
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-puma-homme" data-ea className>
                              Puma
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-kickers-homme"
                              data-ea
                              className
                            >
                              Kickers
                            </a>
                          </li>
                          <li className="all">
                            <a href="/chaussure-marque-homme" data-ea>
                              Encore plus de marques
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Boutiques</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a href="/chaussure-homme-ville" data-ea className>
                              Ville
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-homme-confort"
                              data-ea
                              className
                            >
                              Confort
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-homme-detente"
                              data-ea
                              className
                            >
                              Détente
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-homme-sport" data-ea className>
                              Sport
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-homme-mariage"
                              data-ea
                              className
                            >
                              Mariage
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-homme-grandes-tailles"
                              data-ea
                              className
                            >
                              Grandes tailles
                            </a>
                          </li>
                          <li className="link ">
                            <a href="/chaussure-luxe-homme" data-ea className>
                              Chaussures Luxe
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/marques-ecoresponsables-homme"
                              data-ea
                              className
                            >
                              Mode responsable
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="col">
                        <span className="title">
                          <span>Marques exclusives de Sarenza</span>
                        </span>
                        <ul className="list">
                          <li className="link ">
                            <a
                              href="/chaussure-mr-sarenza-homme"
                              data-ea
                              className
                            >
                              Mr Sarenza
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-marvin-co-homme"
                              data-ea
                              className
                            >
                              Marvin&amp;Co
                            </a>
                          </li>
                          <li className="link ">
                            <a
                              href="/chaussure-i-love-shoes-homme"
                              data-ea
                              className
                            >
                              I Love Shoes
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style dangerouslySetInnerHTML={{ __html: "\n\n" }} />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  promo"
                    data-promo="true"
                    data-ea
                    href="/operation-promo-homme"
                  >
                    La minute météo
                  </a>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
                {/* [RD] - MegaMenu Item men: début */}
                <style dangerouslySetInnerHTML={{ __html: "\n\n" }} />
                <li className="menu-group" data-menu-group={2}>
                  <a
                    className="tab  "
                    data-promo
                    data-ea
                    href="/ventes-privees-chaussures"
                  >
                    Ventes privées
                  </a>
                </li>
                {/* [RD] - MegaMenu Item men : fin */}
              </ul>
              <div id="UserNavPlaceholder" />
            </div>
          </nav>
          {/* Site navigation - End */}
          {/* Search */}
          <form
            className="search-form"
            action="/store/product/search/list/view"
            method="get"
          >
            <input
              type="hidden"
              className="search-origin"
              name="origin"
              defaultValue="s"
            />
            <input
              autoComplete="off"
              autoCorrect="off"
              className="suggest"
              placeholder="Je veux des pantalons..."
              type="search"
              name="search"
            />
            <button className="pictenza pictenza-search" type="submit" />
          </form>
          {/* User navigation - Start */}
          <ul className="user-nav">
            {/* Partner logo - Deprecated ? */}
            <li data-partner>
              {/* module partner-picto */}
              <style
                dangerouslySetInnerHTML={{
                  __html:
                    'li[data-partner] .pictenza-chat:before{content:"";font-size:34px;line-height:13px}li[data-partner] .pictenza-chat span{text-indent:-9999em;display:inline-block}#UserNavPlaceholder .user-nav>li[data-partner]{display:block;max-width:50%;text-align:left}#UserNavPlaceholder .user-nav>li[data-partner]>a{display:none}#UserNavPlaceholder .user-nav>li[data-partner] .pictenza-chat{display:block;border:none;font-weight:700;width:160px}#UserNavPlaceholder .user-nav>li[data-partner] .pictenza-chat:before{content:"\\e624";margin:0 8px 0 0;vertical-align:middle;height:39px;line-height:26px}#UserNavPlaceholder .user-nav>li[data-partner] .pictenza-chat span{text-indent:0}@media screen and (min-width:975px){.no-touch li[data-partner]>a>span{text-indent:-9999em;display:inline-block}.no-touch li[data-partner] .pictenza-chat:before{content:"\\e624"}.no-touch li[data-partner] .pictenza-chat span{display:flex;text-indent:0}}'
                }}
              />
              <a
                className="pictenza pictenza-chat ea-tracker"
                data-ea
                href="/faq"
                target="_blank"
                rel="noopener nofollow"
              >
                <span>FAQ</span>
              </a>
              {/* module partner-picto End */}
            </li>
            {/* Account */}
            <li className="account">
              <a href="/user/view" className="pictenza pictenza-account">
                <span data-rsx="Connecté">Compte</span>
              </a>
              {/* User layer */}
              <ul className="account-layer">
                <li className="sign-in">
                  <a className="east" href="/auth/sign-in/view">
                    Se connecter
                  </a>
                </li>
                <li>
                  <a href="/user/view?zone=orders">Voir mes commandes</a>
                </li>
                <li>
                  <a href="/user/view?zone=orders">Faire un retour</a>
                </li>
                <li>
                  <a href="/user/view?zone=returns">
                    Suivre mes retours et remboursements
                  </a>
                </li>
                <li>
                  <a href="/user/view?zone=addresses">Mon carnet d'adresses</a>
                </li>
                <li>
                  <a href="/user/view?zone=user-infos">
                    Mes informations de connexion
                  </a>
                </li>
                <li>
                  <a href="/customer/alert/new/view">Alertes</a>
                </li>
                <li>
                  <a href="/user/view?zone=newsletters">
                    Mes Newsletters et Alertes
                  </a>
                </li>
                <li>
                  <a className="cookie-set">Mes cookies</a>
                </li>
                <li>
                  <a href="/user/view?zone=vouchers">Mes bons d'achat</a>
                </li>
              </ul>
            </li>
            {/* Alerts */}
            <li className="alerts tooltip-parent">
              <a
                href="/customer/alert/new/view"
                className="pictenza pictenza-alerts"
              >
                <span>Alertes</span>
              </a>
              <div className="tooltip">
                <span className="pictenza pictenza-cancel" />
                <span className="mighty">DECOUVREZ LES ALERTES NOUVEAUTES</span>
                Créez vos alertes pour recevoir chaque semaine par mail les
                dernières nouveautés de vos marques préférées.
              </div>
            </li>
            {/* Favorites */}
            <li className="favorites">
              <a
                data-encrypted="L2N1c3RvbWVyL2Zhdm9yaXRlL2xpc3Qvdmlldw=="
                className="pictenza pictenza-favorites decrypt"
                href="/customer/favorite/list/view"
              >
                <span>Mes favoris</span>
              </a>
            </li>
            {/* Cookies */}
            <li className="cookies">
              <a className="pictenza pictenza-cookie cookie-set">
                <span>Mes cookies</span>
              </a>
            </li>
            {/* Basket */}
            <li className="basket">
              <a
                href="/checkout/basket/view"
                className="pictenza pictenza-basket"
              >
                <span>Panier</span>
              </a>
            </li>
          </ul>
          {/* User navigation - End */}
        </div>
      </header>
    </div>
  );
};

export default Menu;
